task5
Anelagri/moscow_coding_girls pull request #2
Opened 2018-08-02 17:19 UTC by Anelagri

2018-08-02 23:50 UTC, Afelua requested changes

2018-08-02 23:50 UTC, Afelua commented on index.html
> +			<img src="./images/logo.png" alt="" height="30">
Не задан отступ слева и сверху для картинки.

2018-08-02 23:50 UTC, Afelua commented on style.css
> +	width: 1604px;
Картинка должна подстраиваться автоматически по ширине, ее ширину ставить не надо.

2018-08-02 23:50 UTC, Afelua commented on style.css
> +	background-size: contain;
Здесь background-size: cover;

2018-08-02 23:50 UTC, Afelua commented on style.css
> +     display: flex;
Нужно ограничить section по ширине, задать margin: 0 auto; и залить зеленым main.

2018-08-02 23:50 UTC, Afelua commented on index.html
> +	<section class="block-two">
Элементы block-one, block-two ведут себя одинаково, значит, и класс у них должен быть одинаковый.

2018-08-02 23:50 UTC, Afelua commented on style.css
> +.text-two{
Аналогично комментарию выше. Мы не дублируем стили text-one, text-two, если элементы выглядят одинаково. Это должен быть один класс. Проверить везде.

2018-08-02 23:50 UTC, Afelua commented on style.css
> +	width: 404px;
Также выравнивание по центру нужно: text-align: center

2018-08-02 23:50 UTC, Afelua commented on index.html
> + class</div>
Лишнее слово

2018-08-02 23:50 UTC, Afelua commented on style.css
> +	margin: 30px 60 0 40
Не забываем ставить ; 

Проверить везде.

2018-08-02 23:50 UTC, Afelua commented on index.html
> +	<div class="box">
Пустой тег, надо удалить.

2018-08-02 23:50 UTC, Afelua commented on style.css
> +.box{
Неактуальный класс.

2018-08-03 14:59 UTC, Anelagri commented
Лена , вот скопировала то что я сделала.  Это ведь тот main, в котором все
находится? В CSS тоже прописала .my-class{
background: #a2ca28;
}
_____________________________
<main class=“my-class”>
<section class="block-one">
<ul>
<div class="block">

<li class="block-link">
<img src="./images/icon1.svg" alt=""/>
<h2>resources</h2>
<p>Easily manage your inspiration and
work-in-progress by changing images into
projects and sharable clients groups. Easily manage your inspiration and</p>
<a href="#">Explore more</a>
</li>
<li class="block-link">
<img src="./images/icon2.svg" alt=""/>
<h2>Training&Funding</h2>
<p>Easily manage your inspiration and
work-in-progress by dragging images into
projects and sharable clients groups.</p>
<a href="#">Browse training</a>
</li>
<li class="block-link">
<img src="./images/icon3.svg" alt=""/>
<h2>Connect</h2>
<p>Easily manage your inspiration and
work-in-progress by changing images into
projects and sharable clients groups. Easily manage your inspiration.</p>
<a href="#">Connect now</a>
    </li>
<li class="block-link">
<img src="./images/icon4.svg" alt=""/>
<h2>Communicate</h2>
<p>Easily manage your inspiration and
work-in-progress by changing images into
projects and sharable clients groups. Easily </p>
<a href="#">Start now</a>
    </li>
   </div>
              </ul>
<div class="box">
</section>

<section class="block-one">
<div class="text-one">
<h3 class="title-one">it's all about</h3>
<h2 class="title-two">fitness first</h2>
<img width="15"src="./images/icon5.svg" alt=""/>
<p>Lorem ipsum dolor  sit amet,consectetur
adipisicing elit,sed do eiusmod tempor
  incididunt ut labore et dolore magna  aliqua.
Ut enim ad minim veniam,quis nostrud.</p>
<a href="#">Read more</a>
</div>
<img height="394"width="794"src="./images/img1.jpg" alt=""/>
</section>
<section class="block-one">
<img height="394"width="794"src="./images/img2.jpg" alt=""/>
<div class="text-two">
<h3 class="title-one">love your</h3>
<h2 class="title-two">your body</h2>
<img width="15"src="./images/icon5.svg" alt=""/>
<p>Lorem ipsum dolor  sit amet,consectetur
adipisicing elit,sed do eiusmod tempor
  incididunt ut labore et dolore magna  aliqua.
Ut enim ad minim veniam,quis nostrud.</p>
<a href="#">Read more</a>
</div>
</section>
         </div>

</main>

пт, 3 авг. 2018 г. в 2:50, Елена Семенова <notifications@github.com>:

> *@Afelua* requested changes on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/Anelagri/moscow_coding_girls/pull/2#discussion_r207406563>
> :
>
> >  </head>
>  <body>
> -	<header>
> -		<img src="./images/logo.png" alt="">
> +	<header class="background-image">
> +		<div class="header">
> +			<img src="./images/logo.png" alt="" height="30">
>
> Не задан отступ слева и сверху для картинки.
> ------------------------------
>
> In style.css
> <https://github.com/Anelagri/moscow_coding_girls/pull/2#discussion_r207406668>
> :
>
> > +	justify-content: space-between;
> +}
> +
> +
> +.menu{
> +	display: flex;
> +	width: 700px;
> +	justify-content: space-between;
> +	list-style: none;
> +	margin: 30px 60 0 40
> +}
> +
> +.background-image{
> +	background-image: url("./images/background.jpg");
> +	height: 890px;
> +	width: 1604px;
>
> Картинка должна подстраиваться автоматически по ширине, ее ширину ставить
> не надо.
> ------------------------------
>
> In style.css
> <https://github.com/Anelagri/moscow_coding_girls/pull/2#discussion_r207406725>
> :
>
> > +
> +
> +.menu{
> +	display: flex;
> +	width: 700px;
> +	justify-content: space-between;
> +	list-style: none;
> +	margin: 30px 60 0 40
> +}
> +
> +.background-image{
> +	background-image: url("./images/background.jpg");
> +	height: 890px;
> +	width: 1604px;
> +	background-repeat: no-repeat;
> +	background-size: contain;
>
> Здесь background-size: cover;
> ------------------------------
>
> In style.css
> <https://github.com/Anelagri/moscow_coding_girls/pull/2#discussion_r207406928>
> :
>
> > +	color: white;
> +	text-transform: capitalize;
> +	list-style: none;
> +	margin: 30px 40px 0 40px;
> +
> +
> +}
> +.box{
> +	margin: 30px 40px 0 40px
> +}
> +.block{
> +	display: flex;
> +	justify-content: space-between;
> +}
> +.block-one{
> +     display: flex;
>
> Нужно ограничить section по ширине, задать margin: 0 auto; и залить
> зеленым main.
> ------------------------------
>
> In index.html
> <https://github.com/Anelagri/moscow_coding_girls/pull/2#discussion_r207407026>
> :
>
> >  	</section>
> -	<section>
> -		<img width="250"src="./images/img2.jpg" alt=""/>
> -		<div>
> -			<h3>love your</h3>
> -			<h2>your body</h2>
> +	
> +	<section class="block-two">
>
> Элементы block-one, block-two ведут себя одинаково, значит, и класс у них
> должен быть одинаковый.
> ------------------------------
>
> In style.css
> <https://github.com/Anelagri/moscow_coding_girls/pull/2#discussion_r207407236>
> :
>
> > +	height: 394px;
> +	width: 404px;
> +}
> +.title-one{
> +	color: #fd634e;
> +	font-size: 14px;
> +	text-transform: uppercase;
> +}
> +.block-two{
> +	display: flex;
> +	justify-content: space-between;
> +	
> +
> +
> +}
> +.text-two{
>
> Аналогично комментарию выше. Мы не дублируем стили text-one, text-two,
> если элементы выглядят одинаково. Это должен быть один класс. Проверить
> везде.
> ------------------------------
>
> In style.css
> <https://github.com/Anelagri/moscow_coding_girls/pull/2#discussion_r207407299>
> :
>
> > +}
> +.block{
> +	display: flex;
> +	justify-content: space-between;
> +}
> +.block-one{
> +     display: flex;
> +     justify-content: space-between;
> +	
> +
> +
> +}
> +.text-one{
> +	margin: 30px 0px 0 40px;
> +	height: 394px;
> +	width: 404px;
>
> Также выравнивание по центру нужно: text-align: center
> ------------------------------
>
> In index.html
> <https://github.com/Anelagri/moscow_coding_girls/pull/2#discussion_r207407345>
> :
>
> >  		
>  	</section>
> + class</div>
>
> Лишнее слово
> ------------------------------
>
> In style.css
> <https://github.com/Anelagri/moscow_coding_girls/pull/2#discussion_r207407404>
> :
>
> > +	margin: 30px 40px 0 40px;
> +
> +}
> +
> +.header{
> +	display: flex;
> +	justify-content: space-between;
> +}
> +
> +
> +.menu{
> +	display: flex;
> +	width: 700px;
> +	justify-content: space-between;
> +	list-style: none;
> +	margin: 30px 60 0 40
>
> Не забываем ставить ;
>
> Проверить везде.
> ------------------------------
>
> In index.html
> <https://github.com/Anelagri/moscow_coding_girls/pull/2#discussion_r207407492>
> :
>
> >  				<img src="./images/icon4.svg" alt=""/>
>  			<h2>Communicate</h2>
>  			<p>Easily manage your inspiration and
>  				work-in-progress by changing images into
>  			projects and sharable clients groups. Easily </p>
>  			<a href="#">Start now</a>
>  		    </li>
> -		</ul>
> -	</section>
> +		       </div>
> +	              </ul>
> +		
> +	<div class="box">
>
> Пустой тег, надо удалить.
> ------------------------------
>
> In style.css
> <https://github.com/Anelagri/moscow_coding_girls/pull/2#discussion_r207407548>
> :
>
> > +	font-size: 15px;
> +	margin: 10px 0 0 200px;
> +}
> +.benefits{
> +	background: #a2ca28;
> +	
> +}
> +.block-link{
> +	color: white;
> +	text-transform: capitalize;
> +	list-style: none;
> +	margin: 30px 40px 0 40px;
> +
> +
> +}
> +.box{
>
> Неактуальный класс.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Anelagri/moscow_coding_girls/pull/2#pullrequestreview-143014673>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Anjh-bxjI2Ffsis8OILHMDrTTb4-EtFQks5uM5AvgaJpZM4VssSm>
> .
>

2018-08-03 22:42 UTC, Afelua requested changes

2018-08-03 22:42 UTC, Afelua commented on index.html
> +		<div class="text-one">
.text-one и .text-two - тоже имеют одинаковые стили, значит, классы для них одинаковы.

2018-08-03 22:42 UTC, Afelua commented on style.css
> +	height: 394px;
Высоту этого блока не надо задавать, из-за этого отступ между картинками.

2018-08-03 22:42 UTC, Afelua commented on index.html
> +	<main class=“my-class”>
Здесь вставлены не те кавычки (скорее всего, вы наименование класса скопировали из Slack), поэтому код не отрабатывает. Кавычки должны быть как везде.

2018-08-03 22:42 UTC, Afelua commented on style.css
> +}
Лишняя скобка (тоже код не отрабатывает)

2018-08-03 22:42 UTC, Afelua commented on style.css
> +	height: 394px;
После добавления общего зеленого фона фон этого блока нужно сделать белым.

2018-08-05 11:45 UTC, Afelua approved these changes

2018-08-05 16:58 UTC, merged

2018-08-06 15:21 UTC, Anelagri commented
Елена, спасибо! 
Мне очень нравится ваш курс, но я совсем ничего не успеваю. Совсем неожиданно у меня опять командировка на неделю- я не смогу ничего делать здесь. 
Я боюсь не успеть сделать все задания за следующую неделю. Можно мне продлить общение с вами ещё на неделю?
Елена

Отправлено с iPhone

> 5 авг. 2018 г., в 14:45, Елена Семенова <notifications@github.com> написал(а):
> 
> @Afelua approved this pull request.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.