task7
Anelagri/moscow_coding_girls pull request #4
Opened 2018-08-27 14:52 UTC by Anelagri

2018-08-27 15:46 UTC, Afelua requested changes

2018-08-27 15:46 UTC, Afelua commented on index.html
> +<body style="min-width: 1000px;">
Так стили писать нельзя, все делаем через классы.

2018-08-27 15:46 UTC, Afelua commented on style.css
> + .navigation{
Здесь нужно задать отступ справа (прикладываем макет к верхнему правому краю и совмещаем по краям, а не по словам).
<img width="564" alt="screen shot 2018-08-27 at 18 36 19" src="https://user-images.githubusercontent.com/8777546/44669289-30dcf180-aa28-11e8-98bc-35083b724458.png">

2018-08-27 15:46 UTC, Afelua commented on style.css
>  }
Стили для .name_two не применяются из-за этой скобки. Нужно удалить скобку.

2018-08-27 15:46 UTC, Afelua commented on style.css
> +    line-height: 3px;
Задается без пикселей. Здесь значение в 2 должно быть.

2018-08-27 15:46 UTC, Afelua commented on style.css
> +	padding: 29px 0px 16px 0;
Значение отступа снизу должно быть больше. Проверить по макету.

2018-08-27 15:46 UTC, Afelua commented on style.css
> +    padding: 36px 9px 0 54px;
Отступы тут не нужны.

2018-08-27 15:46 UTC, Afelua commented on style.css
> +	left:-5px;
Это не нужно прописывать, только сдвигает изображение.

2018-08-27 15:46 UTC, Afelua commented on style.css
> +	    margin: 0 0 5px 2px;
Тоже лишнее сво-во.

2018-08-27 15:46 UTC, Afelua commented on style.css
> +     height: 398px;
Высоту блоку задавать не надо, она будет определяться автоматически от размера картинки.

2018-08-27 15:46 UTC, Afelua commented on style.css
Проверить размеры элементов формы (инпуты и кнопка) по Pixel Perfect:
<img width="917" alt="screen shot 2018-08-27 at 18 45 13" src="https://user-images.githubusercontent.com/8777546/44669714-59192000-aa29-11e8-82ef-dc2d23fc3c8d.png">

2018-08-27 15:46 UTC, Afelua commented on style.css
> +	width: 20px;
Проверить размеры всех иконок по Pixel Perfect (пока не совпадает):
<img width="278" alt="screen shot 2018-08-27 at 18 46 12" src="https://user-images.githubusercontent.com/8777546/44669763-836add80-aa29-11e8-996f-99650d177ff0.png">

2018-08-28 13:26 UTC, Anelagri commented
Лена, спасибо большое за комментарии, но я не поняла как прописать 1000px в
стиле CSS


> @@ -9,11 +9,11 @@
 	normalize.css"/>
 	<link rel="stylesheet" href="./style.css"/>
 </head>
-<body>
+<body style="min-width: 1000px;">

Так стили писать нельзя, все делаем через классы.

Поставить класс для body? и потом этому классу придать "min-width: 1000px;">

Не могу понять почему у меня все блоки смещены

Когда например, снизу прикладываю в футере макет, то более-менее понятно
что делать с расстояниями итд, но в целом блоки просто разного размера и не
совпадают совсем.

Посылаю вам, что сделала.

Елена

пн, 27 авг. 2018 г. в 18:46, Елена Семенова <notifications@github.com>:

> *@Afelua* requested changes on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/Anelagri/moscow_coding_girls/pull/4#discussion_r213017999>
> :
>
> > @@ -9,11 +9,11 @@
>  	normalize.css"/>
>  	<link rel="stylesheet" href="./style.css"/>
>  </head>
> -<body>
> +<body style="min-width: 1000px;">
>
> Так стили писать нельзя, все делаем через классы.
> ------------------------------
>
> In style.css
> <https://github.com/Anelagri/moscow_coding_girls/pull/4#discussion_r213019092>
> :
>
> >
>
>  }
> -
> + .navigation{
>
> Здесь нужно задать отступ справа (прикладываем макет к верхнему правому
> краю и совмещаем по краям, а не по словам).
> [image: screen shot 2018-08-27 at 18 36 19]
> <https://user-images.githubusercontent.com/8777546/44669289-30dcf180-aa28-11e8-98bc-35083b724458.png>
> ------------------------------
>
> In style.css
> <https://github.com/Anelagri/moscow_coding_girls/pull/4#discussion_r213019766>
> :
>
> >  }
>  .title-one{
>  	color: #fd634e;
>  	font-size: 14px;
>  	text-transform: uppercase;
>  	font-family:OpenSans, sans-serif;
> -	font-weight: 100;
> +	font-weight: 400;
> +	letter-spacing: 2px;
> +	margin-top: 14px;
> +    margin-left: 7px;
> +}
>
>  }
>
> Стили для .name_two не применяются из-за этой скобки. Нужно удалить скобку.
> ------------------------------
>
> In style.css
> <https://github.com/Anelagri/moscow_coding_girls/pull/4#discussion_r213020170>
> :
>
> >
>  }
>  .name_two{
>  	font-family:OpenSans, sans-serif;
>  	font-weight: 400;
> -	padding: 20px 0px 10px 0px;
> -	font-size: 15px;
> -	line-height: 1.5;
> +	padding: 29px 0px 16px 0;
> +    font-size: 13px;
> +    line-height: 3px;
>
> Задается без пикселей. Здесь значение в 2 должно быть.
> ------------------------------
>
> In style.css
> <https://github.com/Anelagri/moscow_coding_girls/pull/4#discussion_r213020397>
> :
>
> >
>  }
>  .name_two{
>  	font-family:OpenSans, sans-serif;
>  	font-weight: 400;
> -	padding: 20px 0px 10px 0px;
> -	font-size: 15px;
> -	line-height: 1.5;
> +	padding: 29px 0px 16px 0;
>
> Значение отступа снизу должно быть больше. Проверить по макету.
> ------------------------------
>
> In style.css
> <https://github.com/Anelagri/moscow_coding_girls/pull/4#discussion_r213020556>
> :
>
> >       margin: 0 auto;
> -
> +    padding: 36px 9px 0 54px;
>
> Отступы тут не нужны.
> ------------------------------
>
> In style.css
> <https://github.com/Anelagri/moscow_coding_girls/pull/4#discussion_r213020797>
> :
>
> > @@ -113,46 +121,58 @@
>  	width: 794px;
>  	height: 394px;
>  	position: relative;
> -	left:0px;
> +	left:-5px;
>
> Это не нужно прописывать, только сдвигает изображение.
> ------------------------------
>
> In style.css
> <https://github.com/Anelagri/moscow_coding_girls/pull/4#discussion_r213020962>
> :
>
> >  }
>  .text-one{
>  	
>      padding: 40px 40px 50px 40px;
>  	text-align: center;
>  	background: #fff;
> +	    margin: 0 0 5px 2px;
>
> Тоже лишнее сво-во.
> ------------------------------
>
> In style.css
> <https://github.com/Anelagri/moscow_coding_girls/pull/4#discussion_r213021437>
> :
>
> >       width: 1188px;
> -     height: 394px;
> +     height: 398px;
>
> Высоту блоку задавать не надо, она будет определяться автоматически от
> размера картинки.
> ------------------------------
>
> In style.css
> <https://github.com/Anelagri/moscow_coding_girls/pull/4#discussion_r213021822>
> :
>
> > @@ -236,6 +286,8 @@
>  	text-transform: uppercase;
>  	font-family:OpenSans, sans-serif;
>  	font-weight: 100;
> +	margin-top: 7px;
> +    margin-left: 4px;
>  }
>
>
> Проверить размеры элементов формы (инпуты и кнопка) по Pixel Perfect:
> [image: screen shot 2018-08-27 at 18 45 13]
> <https://user-images.githubusercontent.com/8777546/44669714-59192000-aa29-11e8-82ef-dc2d23fc3c8d.png>
> ------------------------------
>
> In style.css
> <https://github.com/Anelagri/moscow_coding_girls/pull/4#discussion_r213022198>
> :
>
> >
> -	width: 24px;
> -	height: 24px;
> +	width: 20px;
>
> Проверить размеры всех иконок по Pixel Perfect (пока не совпадает):
> [image: screen shot 2018-08-27 at 18 46 12]
> <https://user-images.githubusercontent.com/8777546/44669763-836add80-aa29-11e8-996f-99650d177ff0.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Anelagri/moscow_coding_girls/pull/4#pullrequestreview-149763869>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Anjh-QESfjkAxdwgI9OaDPRW_F2YsgNfks5uVBRsgaJpZM4WN76Z>
> .
>

2018-08-28 22:11 UTC, Afelua requested changes

2018-08-28 22:11 UTC, Afelua commented on style.css
>  }
Для .block-link прописано невыполняемое свойство:

    color: white text-transform: none;

нужно удалить.

<img width="433" alt="screen shot 2018-08-29 at 00 50 15" src="https://user-images.githubusercontent.com/8777546/44753039-864af880-ab25-11e8-86b6-4d645e5b321d.png">

2018-08-28 22:11 UTC, Afelua commented on style.css
>  }
Также стоит удалить ограничение по высоте 240px.

2018-08-28 22:11 UTC, Afelua commented on style.css
> -
Для .block нужно задать больший padding снизу: padding: 74px 11px 120px 11px;

2018-08-28 22:11 UTC, Afelua commented on style.css
>  	padding: 29px 0px 16px 0;
В текущей реализации отступ padding: 0px 0px 5px 0;

2018-08-28 22:11 UTC, Afelua commented on style.css
Удаляем здесь строку     margin: 0 0 5px 2px;

2018-08-28 22:11 UTC, Afelua commented on style.css
> +	padding: 69px 0px 50px 60px;
Здесь только     padding: 69px 0px; должно быть. Отступ слева не нужен.

2018-08-28 22:11 UTC, Afelua commented on style.css
Здесь должно быть так:

.icon-fb:before {
    background: url(./images/fb.png);
    background-size: 11px 19px;
    width: 11px;
    height: 19px;
    position: absolute;
    top: 16px;
    left: 18px;
}

2018-08-28 22:11 UTC, Afelua commented on style.css
.icon-tw:before {
    background: url(./images/tw.png);
    background-size: 19px 16px;
    width: 19px;
    height: 16px;
    position: absolute;
    top: 17px;
    left: 17px;
}


.icon-yt:before {
    background: url(./images/yt.png);
    background-size: 21px 16px;
    width: 21px;
    height: 16px;
    position: absolute;
    top: 17px;
    left: 14px;
}


.icon-In:before {
    background: url(./images/ln.png);
    background-size: 19px 19px;
    width: 19px;
    height: 19px;
    position: absolute;
    top: 15px;
    left: 17px;
}

2018-08-28 22:11 UTC, Afelua commented on style.css
> +	padding: 74px 11px 0px 11px;
Здесь padding: 110px 11px 0px 11px;

2018-08-30 22:33 UTC, Afelua requested changes

2018-08-30 22:33 UTC, Afelua commented on style.css
> +	padding: 112px 11px 0 11px;
Расстояния тут снизу нет, т.к. в коде стоит ноль снизу: 

padding: 112px 11px 0 11px; = 

112 пикселей сверху
11 пикселей справа
0 пикселей внизу!
11 пикселей слева. 


Чтобы все было корректно, здесь достаточно заменить на     padding: 112px 11px 120px 11px;.

2018-08-30 22:33 UTC, Afelua commented on style.css
У иконки .icon-In остались старые размеры, нужно:

    width: 19px;
    height: 19px;


Иначе сейчас появляются лишние буквы:

<img width="210" alt="screen shot 2018-08-31 at 01 32 44" src="https://user-images.githubusercontent.com/8777546/44882856-cfce4b80-acbd-11e8-8ae1-3b0e94082fb8.png">

2018-08-31 13:07 UTC, Afelua approved these changes

2018-09-02 13:23 UTC, merged